#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Tue Feb 21 20:19:52 CST 2017
# module: ingress
# Action: create
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/logging"
source "${HI_CLI_HOME}/bin/utils"
###############################################################################

function run() {
    log_debug "CMD_LINE: ${CMD_LINE}"
    
    if [ "${app}" == "" ]; then
        if [ "${arg4}" != "" ]; then
            app=${arg4}
        else
            echo "Please input app=your-app"
            exit 1
        fi
    fi
    
    ns=$(kubectl get svc ${app} -o 'jsonpath={.metadata.namespace}')
    port=$(kubectl get svc ${app} -o 'jsonpath={.spec.ports[0].port}')
    
    log_debug "creating ingress for app ${app}, namespace ${ns}, port ${port}  ..."
    
    if [ "${port}" == "" ]; then
        port=80
    fi
    
    if [ "${domain}" == "" ]; then
        domain="${INGRESS_DOMAIN}"
    fi
    
    host="${app}-${ns}.${domain}"
    if [ "${path}" == "" ]; then
        path='/'
    else
        host="dev.${domain}"
    fi
    
    if [ "${domain}" == "" ]; then
        log_warn "You should set your own domain, e.g. export INGRESS_DOMAIN=your.company.com"
        domain="example.com"
    fi
    
    anno_protocol=
    anno_entry=
    if [  "${https}" == "https" ]; then
        anno_protocol="ingress.kubernetes.io/protocol: https"
        anno_entry="traefik.ingress.kubernetes.io/frontend-entry-points: https"
    fi
    
  kubectl apply -f - <<_EOF_
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${app}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/rewrite-target: /
    ${anno_protocol}
    ${anno_entry}
spec:
  rules:
  - host: ${host}
    http:
      paths:
      - path: ${path}
        backend:
          serviceName: ${app}
          servicePort: ${port}
_EOF_
    
    if [[ $? == 0 ]]; then
        log_info "Created ingress for ${app}, URL: http://${app}-${ns}.${domain}"
    else
        log_error "Failed to create ingress"
    fi
    
    result=$?
    
    eval  $1="\${result}"
    eval  $2="\${cli}"
}

###############################################################################



